# https://doc.rust-lang.org/cargo/reference/manifest.html

# âš ï¸ Nazwy w Rust/Cargo majÄ… Å›cisÅ‚e zasady nazewnictwa:
# `mod name` - nazwy plikÃ³w `*.rs` i folderÃ³w w ktÃ³rych siÄ™ znajdujÄ…; Nazwa pliku na dysku = Nazwa moduÅ‚u w kodzie:
#     ğŸ†— MaÅ‚e litery, cyfry, podkreÅ›lniki;           âš ï¸ musi zaczynaÄ‡ siÄ™ od litery lub podkreÅ›lenia;           ğŸš« bez spacji, bez duÅ¼ych liter, bez myÅ›lnikÃ³w, oraz bez: kropek, nawiasÃ³w i innych znakÃ³w;
# `[lib] name`:
#     ğŸ†— MaÅ‚e litery, cyfry, podkreÅ›lniki;           âš ï¸ musi zaczynaÄ‡ siÄ™ od litery lub podkreÅ›lenia;           ğŸš« bez spacji, bez duÅ¼ych liter, bez myÅ›lnikÃ³w, i bez innych znakÃ³w;
# `[package] name`:
#     ğŸ†— MaÅ‚e litery, cyfry, myÅ›lniki;               âš ï¸ musi zaczynaÄ‡ siÄ™ od litery;                            ğŸš« bez spacji, bez duÅ¼ych liter, bez podkreÅ›leÅ„, i bez innych znakÃ³w;
# `[[bin]] name`:
#     ğŸ†— MaÅ‚e litery, cyfry, myÅ›lniki, podkreÅ›lniki; âš ï¸ musi zaczynaÄ‡ siÄ™ od litery lub cyfry lub podkreÅ›lenia; ğŸš« bez spacji, bez duÅ¼ych liter, i bez innych znakÃ³w;

# ğŸŒ² Sprawdzanie struktury projektu
# `cargo install --git https://github.com/mod-by-cis/plot-path-tree-by-pattern --force`  -instaluje narzÄ™dzie do wyÅ›wietlania struktury folderÃ³w projektu;
# `cargo plot-fs-tree -l "." -p "**/*.rs, !target/" --dir-first`              -wyÅ›wietla strukturÄ™ folderÃ³w projektu, pokazujÄ…c tylko pliki `.rs` i ukrywajÄ…c folder `target/`;

# ğŸ—ï¸ Sprawdzanie, Budowanie i Uruchamianie
# ğŸ—ï¸ğŸ” Sprawdzenie kodu bez budowy:
#     `cargo check --bin dev_db`                  lub   `cargo check --bin dev_db_manager`                  - sprawdza kod pod kÄ…tem bÅ‚Ä™dÃ³w bez budowy programu;
#     `cargo clippy --bin dev_db`                 lub   `cargo clippy --bin dev_db_manager`                 - uruchamia narzÄ™dzie Clippy do analizy kodu i sugerowania poprawek;  
#     `cargo clippy --release --bin dev_db`       lub   `cargo clippy --release --bin dev_db_manager`       - uruchamia Clippy w trybie release;
#     `cargo fmt`                                                                                           - automatycznie formatuje kod (wciÄ™cia, nawiasy)
# ğŸ—ï¸ğŸ”§ automatycznie naprawia niektÃ³re problemy (âš ï¸zrÃ³b `commit` przed uÅ¼yciem tego polecenia);
#     `cargo fix --bin dev_db`                    lub   `cargo fix --bin dev_db_manager`                    - automatycznie naprawia niektÃ³re problemy wykryte przez kompilator; 
#     `cargo fix --release --bin dev_db`          lub   `cargo fix --release --bin dev_db_manager`          - automatycznie naprawia niektÃ³re problemy wykryte przez kompilator w trybie release; 
#     `cargo clippy --fix --bin dev_db`           lub   `cargo clippy --fix --bin dev_db_manager`           - automatycznie naprawia niektÃ³re problemy wykryte przez Clippy; 
#     `cargo clippy --release --fix --bin dev_db` lub   `cargo clippy --release --fix --bin dev_db_manager` - automatycznie naprawia niektÃ³re problemy wykryte przez Clippy w trybie release; 
# ğŸ—ï¸â© (debug)   - rezultat w ğŸ“‚`target/debug/`;   Szybka kompilacja, Wolniejszy program; 
#     `cargo run --bin dev_db`                    lub   `cargo run --bin dev_db_manager`                    - buduje i uruchamia program w trybie debug;
#     `cargo build --bin dev_db`                  lub   `cargo build --bin dev_db_manager`                  - buduje program w trybie debug;
# ğŸ—ï¸â–¶ï¸ (release) - rezultat w ğŸ“‚`target/release/`; Wolna kompilacja,  Szybszy program;    
#     `cargo run --release --bin dev_db`          lub   `cargo run --release --bin dev_db_manager`          - buduje i uruchamia program w trybie release;
#     `cargo build --release --bin dev_db`        lub   `cargo build --release --bin dev_db_manager`        - buduje program w trybie release;
# ğŸ—ï¸ğŸ“¡ Opcje sieciowe:
#     `cargo run --offline --bin dev_db`          - uruchamia bez prÃ³by Å‚Ä…czenia z internetem (korzysta z cache);

# ğŸ§¹ Utrzymanie projektu:
#     `cargo clean`                               - Usuwa folder `target/` (zwalnia miejsce, wymusza peÅ‚nÄ… rekompilacjÄ™)
#     `cargo update`                              - Aktualizuje wersje bibliotek w `Cargo.lock` (zgodnie z `Cargo.toml`)
#     `cargo doc --open`                          - Generuje i otwiera dokumentacjÄ™ projektu (kodu i zaleÅ¼noÅ›ci) w przeglÄ…darce; 
#     `cargo doc --no-deps --open`                - Generuje i otwiera dokumentacjÄ™ projektu bez dokumentacji zaleÅ¼noÅ›ci;
#     `cargo doc --document-private-items --open` - Generuje dokumentacjÄ™ TAKÅ»E dla funkcji prywatnych (Å›wietne do nauki!);
#     `cargo tree`                                - WyÅ›wietla drzewo wszystkich bibliotek (kto uÅ¼ywa kogo)
#     `cargo tree -i tokio`                       - "Dlaczego mam w projekcie tokio?" (pokazuje Å›cieÅ¼kÄ™ zaleÅ¼noÅ›ci)
#     `cargo add serde --features derive`         - Dodaje paczkÄ™ (z funkcjami) i wpisuje jÄ… do tego pliku automagicznie
#     `cargo remove serde`                        - Usuwa paczkÄ™ i czyÅ›ci ten plik
#     `cargo audit`                               - (wymaga: cargo install cargo-audit) Sprawdza czy biblioteki nie majÄ… znanych luk bezpieczeÅ„stwa;

# â• przydatne narzÄ™dzia 
# `.\cmd\plotFS.ps1` -wyÅ›wietla strukture folderÃ³w projektu w konsoli PowerShell;

[package]
name = "arboretum" 
version = "0.1.0"
readme = "README.md"
rust-version = "1.93.0"
edition = "2024"
resolver = "3"

[lib]
name = "my_libs" 
path = "src/lib.rs"

# niepotrzebne bo domyÅ›lnie szuka src/main.rs lub src/bin/<nazwa>.rs
# [[bin]]

[dependencies]
# Baza danych SurrealDB w trybie embedded (SurrealKV)
surrealdb = { version = "2.6.0", features = ["kv-surrealkv"] }

# Runtime asynchroniczny (niezbÄ™dny dla SurrealDB)
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }

# Serializacja danych (zmienia struktury Rust <-> JSON/Surreal)
serde = { version = "1.0.228", features = ["derive"] }

# Generowanie ID. v7 jest Å›wietne do baz danych (sortowalne po czasie).
uuid = { version = "1.20.0", features = ["v4", "v7", "serde"] }

#  DO ZARZÄ„DZANIA  MENU???
inquire = "0.9.2"

# Praser plikÃ³w .toml i .xml
toml = "0.9.11"
quick-xml = {"version" = "0.39.0", features = ["serialize"]}

# do obsÅ‚ugi CLI
clap = {"version" = "4.5.56", features = ["derive"]}
thiserror = "2.0.18"
colored = "3.1.1"

